### ISSUE TITLE
Idea: Expand the url/folder structure to include Business Name

### ISSUE THREAD

**Issue by cameronbarker** [graphql/graphql-scalars#21]
I'm super excited about this initiative. Have you thought about allowing businesses to contribute their scalars here? Potentially in a structure like `scalars/business_name/author_name`.

**Comment by andimarek** [comment]
hi @cameronbarker  ... can you explain a bit more why you would like to have another grouping by business name? Can you give a example what business name would be?

To explain our reasoning a bit: we group the scalars by author to avoid any naming conflicts and to also avoid any impression that my `date-time` scalar for example is somehow more or less special to `/cameronbarker/date-time`. The goal of this project is not to define custom scalars, but to give everybody the equal opportunity to define and publish their custom scalars.

**Comment by dondonz** [comment]
Hello, closing this issue as it's been open for a while, if you would like to continue the discussion, feel free to re-open.
