### ISSUE TITLE
Requirements Discussion

### ISSUE THREAD

**Issue by eapache** [graphql/graphql-scalars#4]
Ticket for any discussion of what requirements we want to enforce before we accept a scalar definition to the repo. Off the top of my head:
- Conforms with whatever we decided on for URL/namespacing/versioning: https://github.com/graphql/graphql-scalars/issues/1
- Conforms with whatever rough format we decide on in https://github.com/graphql/graphql-scalars/pull/2
- Some kind of licensing agreement or contributor's agreement or something something legal? #7 

Anything else?

**Comment by dondonz** [comment]
Closing this issue as we have formalised the contribution process, see #13.

EasyCLA has been added to the repo.
